= O Fibonacci App: Documentação técnica
include::included/header-attributes.adoc[]

ifndef::env-github[]
include::included/technical.pt.uris.adoc[]
include::included/technical.pt.attributes.adoc[]

Neste documento são apresentados <<detalhes-tecnicos>> relativos
a implementação do {FibonacciApp}.
Vários desses detalhes de programação são colocados em prática no dia a
dia da construção de aplicativos da startup {FinisherTech}.

include::included/header.pt.adoc[]

<<<
[[licenca-e-codigo-fonte]]
== Licença e código fonte

*{uri-app-github}[O aplicativo "Fibonacci App" é _open source_] e
distribuído sob a {uri-app-github-license}[licença MIT^].*
Seu *código fonte está inteiramente disponível* em dois repositórios
Git: um completo (e privado) e outro público.

[[repo-completo]]
O repositório completo: ::
É utilizado pelos desenvolvedores e {mentorados} da {FinisherTech}.
Nele estão os *commits mais granulares* realizados nessa aplicação.
Contudo, tanto esse repositório quanto o público contemplam os
<<detalhes-tecnicos>> descritos abaixo. +
Essa é uma das formas usadas pela startup para _atrair desenvolvedores
interessados em seus projetos_ de forma que eles entrem para sua equipe.
Esse repositório completo inclui, também, _branches_ com alternativas
de soluções ou algoritmos.

[[repo-publico]]
O {repositorio-publico} ({uri-app-github}): ::
*Contempla commits menos granulares* que talvez sejam (ou serão)
explicados em vídeos disponíveis nos canais
{uri-finishertech-youtube}[Finisher.Tech^] e
{uri-saudeecripto-youtube}[Saúde e Cripto] no YouTube.

Veja a <<todo,lista das funcionalidades>> que serão disponibilizadas em
próximos commits no {repositorio-publico} dessa aplicação.

<<<
[[detalhes-tecnicos]]
== Detalhes Técnicos

Estes são os assuntos cobertos durante a construção do {FibonacciApp}
que já estão disponíveis em commits disponíveis em seu
{repositorio-publico}:

. Construção e otimização de algoritmos:
.. Implementação não recursiva da {serie-de-fibonacci}.
... Várias outras implementações (recursivas ou não) estão
<<repo-completo,repositório completo>>.
.. Busca dos números de Fibonacci que são anterior ou posterior a um
número qualquer.
. [[javascript-e-react]] Desenvolvimento em *JavaScript e
  {uri-react}[React^]*:
.. Inicialização do projeto: utilizando o {uri-cra}[Create React App^]
  (CRA).
.. Organização estruturada das pastas do projeto.
.. Implementação utilizando _Test Driven Development_ (TDD) e
{uri-jest}[Jest^].
.. Codificação de _design_ responsivo e uso de {uri-css-grid-layout}[CSS
Grid Layout^].
.. Codificação de páginas e componentes em React.
.. Uso de {uri-react-hooks}[React Hooks^]: _useState_,
_useEffect_, _useCallback_, _useMemo_, etc.
.. Uso do {uri-react-router}[React Router^] (em sua versão 6).
.. Uso do {uri-react-device-detect}[react-device-detect^] para detecção
de dispositivos e adequação desse app a dispositivos móveis.
.. Internacionalização utilizando o {uri-react-i18next}[react-i18next^].
.. Seleção de temas (_Light_ ou _Dark_) através de ajuste dinâmico de
  {uri-css-custom-properties}[CSS Custom Properties^].
.. Criação de componentes específicos para separar as funcionalidades de
internacionalização e de seleção de tema.
.. Desenho da função Fibonacci usando o {uri-katex}[Katex^] e
{uri-react-katex}[react-katex^].
. Deploy em produção:
.. Feito no {uri-github-pages}[GitHub Pages^] através do _package_
{uri-gh-pages-npm}[gh-pages].
. <<documentacao>>.

<<<
[[execucao-local]]
== Execução local

....
$ npm install
$ npm start
....

[[documentacao]]
== Documentação

Esse documento técnico, e todos os outros que foram gerados em
{uri-app-github-docs}, são construídos de forma programática.
O termo técnico para isso em inglês é _{uri-doc-as-code}[Docs as Code]_.
Os documentos neste projeto são:

. Escritos no {uri-paulojeronimo-asciidoc}[formato AsciiDoc^].
.. Contém definições para visualização em diferentes formatos (HTML,
PDF) e no ambiente do GitHub (`env-github`).
.. A equação matemática da função Fibonacci é escrita {uri-latex}[LaTeX]
e convertida para uma imagem no formato {uri-svg}[SVG^] (arquivo
{uri-app-github-docs}/images/fibonacci.svg[fibonacci.svg]).
Esse arquivo é, então, usado na geração de PDFs.
.. Os links referenciados nos documentos são escritos a partir de um
arquivo escrito no formato {uri-yaml}[YAML^] (
{uri-app-github-docs}/fibonacci-refs.yaml[fibonacci-refs.yaml]).
A partir dele as referências são geradas no formato AsciiDoc.
. Gerados nos formatos HTML e PDF através de um
  {uri-app-github-docs-build}[script escrito em Bash^] que utiliza o
{uri-docker}[Docker] para executar o {uri-asciidoctor}[Asciidoctor^].

=== Processos de geração

Há dois processos de geração dos documentos.

No _default_, sua geração é feita para o acesso via
http://localhost:3000/fibonacci-app/docs.
Essa URL é a padrão ao iniciar o {FibonacciApp} localmente através do
`npm start`.
Nesse caso, o commando para geração é este:

....
$ docs/build.sh
....

Outro processo é para a atualização/ visualização dos documentos de
forma _detached_, ou seja, sem a necessidade de o {FibonacciApp} estar
em execução, mas com um servidor HTTP em execução em
http://localhost:3000.
Essa será a URL base para os documentos no caso de você executar estes
comandos:

....
$ docs/build.sh detached
$ serve -s public/docs &> /dev/null & # <1> <2>
....
<1> Inicia um servidor HTTP local (instalado via `npm install
-g serve`) em background.
<2> Veja {uri-gist-httpd-servers}[alternativas p/ execução de um
servidor HTTP^] utilizando diferentes linguagens de programação.


[[deploy-gh-pages]]
== Deploy no GitHub Pages

....
$ npm run deploy
....

WARNING: Esse procedimento só será executado com sucesso se você possuir
permissão para alterar a {uri-app-github-gh-pages}[branch gh-pages^] da
aplicação!

<<<
[[todo]]
== TODO

* *_Refactorings_*:
** +++<del>+++Separar os componentes em `FibonacciNumbers.js` em
diferentes arquivos e utilizar o _useContext_+++</del>+++ (_Feito_).
** Utilizar o {uri-styled-components}[Styled Components].
** Melhorar o _design_ do frontend (estilização no geral).

* *Novas funcionalidades*:
** Salvar os números de Fibonacci que uma pessoa utiliza em um _backend_
({uri-firebase}[Firebase] ou {uri-supabase}[Supabase]) que estará
acessível (para leitura) para todos.
*** Possibilitar a pesquisa dos números Fibonacci registrados por um
usuário específico.
*** Um usuário não poderá editar as descrições associadas a números
cadastros por outros usuários.
** Desenhar a espiral de Fibonacci (com o {uri-p5js}[p5.js] ou o
{uri-d3js}[d3.js]) conforme a navegação do usuário pelos números da
série na página Numbers.
*** Esse desenho deverá ser interativo (obedecendo a navegação do
usuário nos números da série).
** Possibilitar que o usuário se registre utilizando seu email ou
telefone.
*** Se o usuário for brasileiro e informar um CEP, o aplicativo
consulará o {uri-viacep}[ViaCEP] para auxiliar o usuário a entrar com
seu endereço completo.
** Exigir o login do usuário para que ele possa registrar seus números.
*** Utilizar JWT para autenticação do usuário e, também, OAuth para
possibilitar login social.
** Acrescenter algumas rotas externas (ou que estejam em `/public`).
Exemplos:
*** `{uri-app}/public/technical.pt.html` <- deve
enviar o usuário para a página `technical.pt.html` localizado na pasta
`public` junto aos fontes do projeto. Da mesma forma,
{uri-app}/public/xpto.json deve
possibilitar o browser apresentar esse arquivo, caso ele exista na pasta
`public`.
*** {uri-app}/github <- deve redirecionar o
usuário para o {repositorio-publico}.
** *_Premium_ (para os {mentorados})*:
*** Versão que altera o _backend_ para uso da
{uri-paulojeronimo-blockchain}[Blockchain] do
{uri-paulojeronimo-ethereum}[Ethereum].

* *Bugs conhecidos:*
** Ao se efetuar uma troca da linguagem é possível notar que o botão
que indica qual o fator de incremento/decremento não troca de vírgula
para ponto (ou vice-versa).
endif::env-github[]

ifdef::env-github[]
Leia o arquivo https://finisher.tech/fibonacci-app/docs/technical.pt.pdf[]
endif::[]
